trusts = T{
   [1]={japanese="シャントット",english="Shantotto",name="Shantotto",models=3000},
   [2]={japanese="ナジ",english="Naji",name="Naji",models=3001},
   [3]={japanese="クピピ",english="Kupipi",name="Kupipi",models=3002},
   [4]={japanese="エグセニミル",english="Excenmille",name="Excenmille",models=3003},
   [5]={japanese="アヤメ",english="Ayame",name="Ayame",models=3004},
   [6]={japanese="ナナー・ミーゴ",english="Nanaa Mihgo",name="NanaaMihgo",models=3005},
   [7]={japanese="クリルラ",english="Curilla",name="Curilla",models=3006},
   [8]={japanese="フォルカー",english="Volker",name="Volker",models=3007},
   [9]={japanese="アジドマルジド",english="Ajido-Marujido",name="Ajido-Marujido",models=3008},
   [10]={japanese="トリオン",english="Trion",name="Trion",models=3009},
   [11]={japanese="ザイド",english="Zeid",name="Zeid",models=3010},
   [12]={japanese="ライオン",english="Lion",name="Lion",models=3011},
   [13]={japanese="テンゼン",english="Tenzen",name="Tenzen",models=3012},
   [14]={japanese="ミリ・アリアポー",english="Mihli Aliapoh",name="MihliAliapoh",models=3013},
   [15]={japanese="ヴァレンラール",english="Valaineral",name="Valaineral",models=3014},
   [16]={japanese="ヨアヒム",english="Joachim",name="Joachim",models=3015},
   [17]={japanese="ナジャ・サラヒム",english="Naja Salaheem",name="NajaSalaheem",models=3016},
   [18]={japanese="プリッシュ",english="Prishe",name="Prishe",models=3017},
   [19]={japanese="ウルミア",english="Ulmia",name="Ulmia",models=3018},
   [20]={japanese="スカリーZ",english="Shikaree Z",name="ShikareeZ",models=3019},
   [21]={japanese="チェルキキ",english="Cherukiki",name="Cherukiki",models=3020},
   [22]={japanese="アイアンイーター",english="Iron Eater",name="IronEater",models=3021},
   [23]={japanese="ゲッショー",english="Gessho",name="Gessho",models=3022},
   [24]={japanese="ガダラル",english="Gadalar",name="Gadalar",models=3023},
   [25]={japanese="ライニマード",english="Rainemard",name="Rainemard",models=3024},
   [26]={japanese="イングリッド",english="Ingrid",name="Ingrid",models=3025},
   [27]={japanese="レコ・ハボッカ",english="Lehko Habhoka",name="LehkoHabhoka",models=3026},
   [28]={japanese="ナシュメラ",english="Nashmeira",name="Nashmeira",models=3027},
   [29]={japanese="ザザーグ",english="Zazarg",name="Zazarg",models=3028},
   [30]={japanese="アヴゼン",english="Ovjang",name="Ovjang",models=3029},
   [31]={japanese="メネジン",english="Mnejing",name="Mnejing",models=3030},
   [32]={japanese="サクラ",english="Sakura",name="Sakura",models=3031},
   [33]={japanese="ルザフ",english="Luzaf",name="Luzaf",models=3032},
   [34]={japanese="ナジュリス",english="Najelith",name="Najelith",models=3033},
   [35]={japanese="アルド",english="Aldo",name="Aldo",models=3034},
   [36]={japanese="モーグリ",english="Moogle",name="Moogle",models=3035},
   [37]={japanese="ファブリニクス",english="Fablinix",name="Fablinix",models=3036},
   [38]={japanese="マート",english="Maat",name="Maat",models=3037},
   [39]={japanese="D.シャントット",english="D. Shantotto",name="D.Shantotto",models=3038},
   [40]={japanese="星の神子",english="Star Sibyl",name="StarSibyl",models=3039},
   [41]={japanese="カラハバルハ",english="Karaha-Baruha",name="Karaha-Baruha",models=3040},
   [42]={japanese="シド",english="Cid",name="Cid",models=3041},
   [43]={japanese="ギルガメッシュ",english="Gilgamesh",name="Gilgamesh",models=3042},
   [44]={japanese="アレヴァト",english="Areuhat",name="Areuhat",models=3043},
   [45]={japanese="セミ・ラフィーナ",english="Semih Lafihna",name="SemihLafihna",models=3044},
   [46]={japanese="エリヴィラ",english="Elivira",name="Elivira",models=3045},
   [47]={japanese="ノユリ",english="Noillurie",name="Noillurie",models=3046},
   [48]={japanese="ルー・マカラッカ",english="Lhu Mhakaracca",name="LhuMhakaracca",models=3047},
   [49]={japanese="フェリアスコフィン",english="Ferreous Coffin",name="FerreousCoffin",models=3048},
   [50]={japanese="リリゼット",english="Lilisette",name="Lilisette",models=3049},
   [51]={japanese="ミュモル",english="Mumor",name="Mumor",models=3050},
   [52]={japanese="ウカ・トトゥリン",english="Uka Totlihn",name="UkaTotlihn",models=3051},
   [53]={japanese="クララ",english="Klara",name="Klara",models=3053},
   [54]={japanese="ロマー・ミーゴ",english="Romaa Mihgo",name="RomaaMihgo",models=3054},
   [55]={japanese="クイン・ハスデンナ",english="Kuyin Hathdenna",name="KuyinHathdenna",models=3055},
   [56]={japanese="ラーアル",english="Rahal",name="Rahal",models=3056},
   [57]={japanese="コルモル",english="Koru-Moru",name="Koru-Moru",models=3057},
   [58]={japanese="ピエージェ(UC)",english="Pieuje (UC)",name="Pieuje",models=3058},
   [59]={japanese="I.シールド(UC)",english="I. Shield (UC)",name="InvincibleShld",models=3060},
   [60]={japanese="アプルル(UC)",english="Apururu (UC)",name="Apururu",models=3061},
   [61]={japanese="ジャコ(UC)",english="Jakoh (UC)",name="JakohWahcondalo",models=3062},
   [62]={japanese="フラヴィリア(UC)",english="Flaviria (UC)",name="Flaviria",models=3059},
   [63]={japanese="ウェイレア",english="Babban",name="Babban",models=3067},
   [64]={japanese="アベンツィオ",english="Abenzio",name="Abenzio",models=3068},
   [65]={japanese="ルガジーン",english="Rughadjeen",name="Rughadjeen",models=3069},
   [66]={japanese="クッキーチェブキー",english="Kukki-Chebukki",name="Kukki-Chebukki",models=3070},
   [67]={japanese="マルグレート",english="Margret",name="Margret",models=3071},
   [68]={japanese="チャチャルン",english="Chacharoon",name="Chacharoon",models=3072},
   [69]={japanese="レイ・ランガヴォ",english="Lhe Lhangavo",name="LheLhangavo",models=3073},
   [70]={japanese="アシェラ",english="Arciela",name="Arciela",models=3074},
   [71]={japanese="マヤコフ",english="Mayakov",name="Mayakov",models=3075},
   [72]={japanese="クルタダ",english="Qultada",name="Qultada",models=3076},
   [73]={japanese="アーデルハイト",english="Adelheid",name="Adelheid",models=3077},
   [74]={japanese="アムチュチュ",english="Amchuchu",name="Amchuchu",models=3078},
   [75]={japanese="ブリジッド",english="Brygid",name="Brygid",models=3079},
   [76]={japanese="ミルドリオン",english="Mildaurion",name="Mildaurion",models=3080},
   [77]={japanese="ハルヴァー",english="Halver",name="Halver",models=3087},
   [78]={japanese="ロンジェルツ",english="Rongelouts",name="Rongelouts",models=3088},
   [79]={japanese="レオノアーヌ",english="Leonoyne",name="Leonoyne",models=3089},
   [80]={japanese="マクシミリアン",english="Maximilian",name="Maximilian",models=3090},
   [81]={japanese="カイルパイル",english="Kayeel-Payeel",name="Kayeel-Payeel",models=3091},
   [82]={japanese="ロベルアクベル",english="Robel-Akbel",name="Robel-Akbel",models=3092},
   [83]={japanese="クポフリート",english="Kupofried",name="Kupofried",models=3093},
   [84]={japanese="セルテウス",english="Selh\'teus",name="Selh\'teus",models=3094},
   [85]={japanese="ヨランオラン(UC)",english="Yoran-Oran (UC)",name="Yoran-Oran",models=3095},
   [86]={japanese="シルヴィ(UC)",english="Sylvie (UC)",name="Sylvie",models=3096},
   [87]={japanese="アブクーバ",english="Abquhbah",name="Abquhbah",models=3098},
   [88]={japanese="バラモア",english="Balamor",name="Balamor",models=3099},
   [89]={japanese="オーグスト",english="August",name="August",models=3100},
   [90]={japanese="ロスレーシャ",english="Rosulatia",name="Rosulatia",models=3101},
   [91]={japanese="テオドール",english="Teodor",name="Teodor",models=3103},
   [92]={japanese="ウルゴア",english="Ullegore",name="Ullegore",models=3105},
   [93]={japanese="マッキーチェブキー",english="Makki-Chebukki",name="Makki-Chebukki",models=3106},
   [94]={japanese="キング・オブ・ハーツ",english="King of Hearts",name="KingOfHearts",models=3107},
   [95]={japanese="モリマー",english="Morimar",name="Morimar",models=3108},
   [96]={japanese="ダラクァルン",english="Darrcuiln",name="Darrcuiln",models=3109},
   [97]={japanese="アークHM",english="AAHM",name="ArkHM",models=3113},
   [98]={japanese="アークEV",english="AAEV",name="ArkEV",models=3114},
   [99]={japanese="アークMR",english="AAMR",name="ArkMR",models=3115},
   [100]={japanese="アークTT",english="AATT",name="ArkTT",models=3116},
   [101]={japanese="アークGK",english="AAGK",name="ArkGK",models=3117},
   [102]={japanese="イロハ",english="Iroha",name="Iroha",models=3111},
   [103]={japanese="ユグナス",english="Ygnas",name="Ygnas",models=3118},
   [104]={japanese="エグセニミルII",english="Excenmille [S]",name="Excenmille",models=3052},
   [105]={japanese="アヤメ(UC)",english="Ayame (UC)",name="Ayame",models=3063},
   [106]={japanese="マート(UC)",english="Maat (UC)",name="Maat",models=3064}, --expected models
   [107]={japanese="アルド(UC)",english="Aldo (UC)",name="Aldo",models=3065}, --expected models
   [108]={japanese="ナジャ(UC)",english="Naja (UC)",name="NajaSalaheem",models=3066},
   [109]={japanese="ライオンII",english="Lion II",name="Lion",models=3081},
   [110]={japanese="ザイドII",english="Zeid II",name="Zeid",models=3086},
   [111]={japanese="プリッシュII",english="Prishe II",name="Prishe",models=3082},
   [112]={japanese="ナシュメラII",english="Nashmeira II",name="Nashmeira",models=3083},
   [113]={japanese="リリゼットII",english="Lilisette II",name="Lilisette",models=3084},
   [114]={japanese="テンゼンII",english="Tenzen II",name="Tenzen",models=3097},
   [115]={japanese="ミュモルII",english="Mumor II",name="Mumor",models=3104},
   [116]={japanese="イングリッドII",english="Ingrid II",name="Ingrid",models=3102},
   [117]={japanese="アシェラII",english="Arciela II",name="Arciela",models=3085},
   [118]={japanese="イロハII",english="Iroha II",name="Iroha",models=3112},
   [119]={japanese="シャントットII",english="Shantotto II",name="Shantotto",models=3110},
   [120]={japanese="コーネリア",english="Cornelia",name="Cornelia",models=3119}, --goodbye, my love
   [121]={japanese="モンブロー",english="Monberaux",name="Monberaux",models=3120},
   [122]={japanese="マツイP",english="Matsui-P",name="Matsui-P",models=3121},
}